import { useAuth } from '../context/AuthContext';

/* ── Mirror of backend ROLE_PERMISSIONS ── */
const ROLE_PERMISSIONS = {
  admin: {
    manageStaff:     true,
    viewFinance:     true,
    manageInventory: true,
    bill:            true,
    viewReports:     true,
    managePatients:  true,
    viewClinical:    true,
    nurseStation:    true,
    labTests:        true,
    manageIPD:       true,
    manageOPD:       true,
    viewAuditLog:    true,
    storeSettings:   true,
    purchaseOrders:  true,
    deleteRecords:   true,
    manageInsurance: true,
    managePayroll:   true,
    accessAI:        true,
    drap:            true,
    broadcast:       true,
    rag:             true,
    settings:        true,
  },
  doctor: {
    manageStaff:     false,
    viewFinance:     false,
    manageInventory: false,
    bill:            false,
    viewReports:     true,
    managePatients:  true,
    viewClinical:    true,
    nurseStation:    false,
    labTests:        true,
    manageIPD:       true,
    manageOPD:       true,
    viewAuditLog:    false,
    storeSettings:   false,
    purchaseOrders:  false,
    deleteRecords:   false,
    manageInsurance: false,
    managePayroll:   false,
    accessAI:        true,
    drap:            false,
    broadcast:       false,
    rag:             true,
    settings:        false,
  },
  pharmacist: {
    manageStaff:     false,
    viewFinance:     false,
    manageInventory: true,
    bill:            true,
    viewReports:     false,
    managePatients:  true,
    viewClinical:    false,
    nurseStation:    false,
    labTests:        true,
    manageIPD:       false,
    manageOPD:       false,
    viewAuditLog:    false,
    storeSettings:   false,
    purchaseOrders:  true,
    deleteRecords:   false,
    manageInsurance: false,
    managePayroll:   false,
    accessAI:        false,
    drap:            false,
    broadcast:       false,
    rag:             true,
    settings:        false,
  },
  nurse: {
    manageStaff:     false,
    viewFinance:     false,
    manageInventory: false,
    bill:            false,
    viewReports:     false,
    managePatients:  true,
    viewClinical:    true,
    nurseStation:    true,
    labTests:        false,
    manageIPD:       false,
    manageOPD:       false,
    viewAuditLog:    false,
    storeSettings:   false,
    purchaseOrders:  false,
    deleteRecords:   false,
    manageInsurance: false,
    managePayroll:   false,
    accessAI:        false,
    drap:            false,
    broadcast:       false,
    rag:             true,
    settings:        false,
  },
  receptionist: {
    manageStaff:     false,
    viewFinance:     false,
    manageInventory: false,
    bill:            true,
    viewReports:     false,
    managePatients:  true,
    viewClinical:    false,
    nurseStation:    false,
    labTests:        false,
    manageIPD:       false,
    manageOPD:       true,
    viewAuditLog:    false,
    storeSettings:   false,
    purchaseOrders:  false,
    deleteRecords:   false,
    manageInsurance: false,
    managePayroll:   false,
    accessAI:        false,
    drap:            false,
    broadcast:       false,
    rag:             false,
    settings:        false,
  },
  lab_technician: {
    manageStaff:     false,
    viewFinance:     false,
    manageInventory: false,
    bill:            false,
    viewReports:     false,
    managePatients:  true,
    viewClinical:    false,
    nurseStation:    false,
    labTests:        true,
    manageIPD:       false,
    manageOPD:       false,
    viewAuditLog:    false,
    storeSettings:   false,
    purchaseOrders:  false,
    deleteRecords:   false,
    manageInsurance: false,
    managePayroll:   false,
    accessAI:        false,
    drap:            false,
    broadcast:       false,
    rag:             false,
    settings:        false,
  },
};

export const usePermissions = () => {
  const { user } = useAuth();
  const role = user?.role || 'pharmacist';
  const can  = ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.pharmacist;

  return {
    role,
    can,
    isAdmin:         role === 'admin',
    isDoctor:        role === 'doctor',
    isPharmacist:    role === 'pharmacist',
    isNurse:         role === 'nurse',
    isReceptionist:  role === 'receptionist',
    isLabTech:       role === 'lab_technician',
    isClinical:      ['admin','doctor','nurse'].includes(role),
  };
};
